using System.Text;
using FaultTracePC.Core.Analysis;

namespace FaultTracePC.Core.Report;

/// <summary>
/// Génère le rapport de diagnostic HTML autonome (aucune ressource externe),
/// en français, lisible par un non-spécialiste mais complet pour un technicien.
/// </summary>
public static class HtmlReportGenerator
{
    /// <summary>
    /// Nom de fichier d'un rapport — UNE seule formule pour les trois écrivains :
    /// application, ligne de commande et service.
    ///
    /// LE DÉFAUT QU'ELLE SUPPRIME, constaté le 30/08/2026 sur un rapport réel :
    /// la ligne de commande écrivait « Diagnostic_TECH-INFO-2025_… » et
    /// l'application « Diagnostic_PC_… », un reliquat d'avant que le nom de
    /// machine existe. Deux familles de noms pour la même chose dans le même
    /// dossier — et, sur un partage où plusieurs postes déposent leurs rapports,
    /// deux machines analysant à la même minute s'écrasaient l'une l'autre.
    /// </summary>
    public static string NomDuRapport(DiagnosticReport r) =>
        $"Diagnostic_{NomDeMachineSur(r.System?.MachineName)}_{r.GeneratedAt:yyyy-MM-dd_HHmm}.html";

    /// <summary>
    /// Nom de machine réduit à ce que <see cref="EstUnNomDeRapport"/> accepte :
    /// lettres, chiffres, tiret et tiret bas. Tout le reste devient un tiret bas.
    /// L'invariant compte plus que l'esthétique : un nom que nous produisons doit
    /// toujours passer notre propre contrôle, sinon la console ne pourrait plus
    /// télécharger le rapport d'une machine au nom exotique.
    /// </summary>
    public static string NomDeMachineSur(string? machineName)
    {
        var brut = string.IsNullOrWhiteSpace(machineName) ? Environment.MachineName : machineName.Trim();
        var propre = string.Concat(brut.Select(c => char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '_'));
        return propre.Length == 0 ? "PC" : propre;
    }

    /// <summary>
    /// Contrôle du nom réclamé par la console avant de servir un fichier.
    ///
    /// C'est d'abord un garde-fou de sécurité : il n'accepte ni point, ni
    /// séparateur de chemin, ni deux-points, donc aucune traversée de répertoire.
    /// Il accepte les DEUX formes, l'ancienne « Diagnostic_PC_… » et la nouvelle
    /// qui porte le nom de machine — sans quoi les rapports déjà déposés dans le
    /// dossier partagé deviendraient invisibles du jour au lendemain.
    /// </summary>
    public static bool EstUnNomDeRapport(string? nom) =>
        nom is not null && NomDeRapportRx.IsMatch(nom);

    private static readonly System.Text.RegularExpressions.Regex NomDeRapportRx =
        new(@"^Diagnostic_[\w\-]+\.html$", System.Text.RegularExpressions.RegexOptions.Compiled);

    public static string Generate(DiagnosticReport r)
    {
        var sb = new StringBuilder(64 * 1024);
        sb.Append("<!DOCTYPE html><html lang=\"fr\"><head><meta charset=\"utf-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append(Lang.T($"<title>Diagnostic {H(r.System.MachineName)} — {r.GeneratedAt:dd/MM/yyyy}</title>",
                         $"<title>Diagnosis {H(r.System.MachineName)} — {r.GeneratedAt:yyyy-MM-dd}</title>"));
        // Mode simple par défaut : l'essentiel d'abord, les détails techniques sur demande.
        sb.Append("<style>").Append(Css).Append("</style></head><body class=\"simple\">");

        Header(sb, r);
        VerdictBanner(sb, r);
        GuidedHint(sb, r);
        ComparisonSection(sb, r);
        Findings(sb, r);
        RepairSection(sb, r);
        FlightSection(sb, r);
        BsodSection(sb, r);
        DumpSection(sb, r);
        ProcessesSection(sb, r);
        EventsSection(sb, r);
        SystemSection(sb, r);
        SmartSection(sb, r);
        DriversSection(sb, r);
        ReliabilitySection(sb, r);
        ErrorsSection(sb, r);

        sb.Append(Lang.T($"<footer>Généré par <strong>FaultTracePC</strong> v{UpdateChecker.CurrentVersion} le {r.GeneratedAt:dd/MM/yyyy à HH:mm} — période analysée : {r.ScanPeriodDays} jours. ", $"<footer>Generated by <strong>FaultTracePC</strong> v{UpdateChecker.CurrentVersion} on {r.GeneratedAt:yyyy-MM-dd HH:mm} — period analysed: {r.ScanPeriodDays} days. "));
        sb.Append(Lang.T("Les niveaux de confiance sont indiqués honnêtement : une confiance « faible » signale une piste, pas une preuve.</footer>", "Confidence levels are stated honestly: “low” confidence marks a lead, not a proof.</footer>"));
        sb.Append("<script>const FTPC_L={complet:").Append(Js(BasculeVersComplet))
          .Append(",simple:").Append(Js(BasculeVersSimple)).Append("};")
          .Append(FilterJs).Append("</script>");
        sb.Append("</body></html>");
        return sb.ToString();
    }

    /// <summary>
    /// Écrit le rapport (et le script de réparation s'il y a des problèmes)
    /// dans Documents\FaultTracePC et retourne le chemin du rapport HTML.
    /// </summary>
    public static string WriteToDisk(DiagnosticReport r)
    {
        // Le script d'abord : le rapport HTML référence son chemin et embarque son contenu.
        RepairScriptGenerator.WriteToDisk(r); // renseigne RepairScriptPath + RepairLauncherPath

        var dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "FaultTracePC");
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, NomDuRapport(r));
        File.WriteAllText(path, Generate(r), Encoding.UTF8);

        // Copie vers le dossier partagé (servi par l'API du mode Client) — best effort.
        try
        {
            Directory.CreateDirectory(RemoteConfig.SharedReportsDir);
            File.Copy(path, Path.Combine(RemoteConfig.SharedReportsDir, Path.GetFileName(path)), overwrite: true);
        }
        catch { /* partage indisponible : le rapport local reste la référence */ }

        return path;
    }

    // ------------------------------------------------------------------

    private static void Header(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append("<header><div class=\"brand\">");
        sb.Append($"<img src=\"{Branding.LogoDataUri}\" alt=\"FaultTracePC\" width=\"48\" height=\"48\">");
        sb.Append(Lang.T("<h1>FaultTracePC — Rapport de diagnostic</h1></div>", "<h1>FaultTracePC — Diagnostic report</h1></div>"));
        sb.Append(Lang.T($"<p class=\"sub\">Machine <strong>{H(r.System.MachineName)}</strong> · {H(r.System.Os.Caption)} {H(r.System.Os.DisplayVersion)} (build {H(r.System.Os.BuildNumber)}) · généré le {r.GeneratedAt:dd/MM/yyyy à HH:mm} · période : {r.ScanPeriodDays} jours</p>", $"<p class=\"sub\">Machine <strong>{H(r.System.MachineName)}</strong> · {H(r.System.Os.Caption)} {H(r.System.Os.DisplayVersion)} (build {H(r.System.Os.BuildNumber)}) · generated on {r.GeneratedAt:yyyy-MM-dd HH:mm} · period: {r.ScanPeriodDays} days</p>"));
        // Fraîcheur : un rapport daté d'aujourd'hui laisse croire qu'il décrit
        // aujourd'hui. Sur une machine éteinte depuis des mois, il décrit un passé
        // lointain, et rien à la lecture ne permettait de s'en apercevoir.
        sb.Append("<p class=\"sub small\">")
          .Append(H(Analysis.DataFreshness.Sentence(Analysis.DataFreshness.Of(r), r.GeneratedAt)))
          .Append("</p>");
        sb.Append("<button id=\"mode-toggle\" class=\"btn2\" type=\"button\">").Append(H(BasculeVersComplet)).Append("</button>");
        sb.Append("</header>");
    }

    private static void VerdictBanner(StringBuilder sb, DiagnosticReport r)
    {
        var cls = r.Findings.Any(f => f.Severity == Severity.Critical) ? "crit"
                : r.Findings.Any(f => f.Severity == Severity.Warning) ? "warn" : "ok";
        sb.Append($"<div class=\"verdict {cls}\"><div class=\"verdict-label\">Verdict</div><div class=\"verdict-text\">{H(r.Verdict)}</div></div>");
    }

    /// <summary>
    /// « Et maintenant, je fais quoi ? »
    ///
    /// Un rapport de diagnostic laisse souvent son lecteur avec un constat et aucun
    /// point de départ. Ce bandeau indique qu'un assistant guidé existe dans le
    /// logiciel, juste sous le verdict — c'est-à-dire à l'endroit exact où la
    /// question se pose. Il n'apparaît que s'il y a réellement quelque chose à
    /// traiter : sur une machine saine, ce serait du bruit.
    /// </summary>
    private static void GuidedHint(StringBuilder sb, DiagnosticReport r)
    {
        bool somethingToDo = r.Findings.Any(f => f.Severity is Severity.Critical or Severity.Warning);
        if (!somethingToDo) return;

        var driver = r.Findings.FirstOrDefault(f =>
            f.Category == FaultCategory.Driver && f.Severity == Severity.Critical);

        sb.Append("<div class=\"guided\">");
        sb.Append(Lang.T("<div class=\"guided-t\">Tu ne sais pas par où commencer ?</div>", "<div class=\"guided-t\">Not sure where to start?</div>"));
        sb.Append(Lang.T(
            "<p>Dans FaultTracePC, le bouton <strong>« Je ne sais pas ce que j'ai »</strong> enchaîne tout seul "
            + "ce qu'il est possible de faire sans risque : point de restauration, examen, réparation des fichiers "
            + "système et de l'image Windows, contrôle du disque — puis il revérifie et conclut en une phrase. "
            + "Ce qui demande une décision t'est proposé à la fin, une action à la fois, avec sa raison.</p>",
            "<p>In FaultTracePC, the <strong>“I don't know what's wrong with it”</strong> button runs, on its own, "
            + "everything that can be done without risk: restore point, examination, repair of the system files "
            + "and of the Windows image, disk check — then it checks again and concludes in one sentence. "
            + "Anything needing a decision is offered at the end, one action at a time, with its reason.</p>"));

        if (driver is not null)
            sb.Append(Lang.T(
                "<p><strong>Dans ton cas</strong>, le problème principal vient d'un pilote. L'assistant ne le "
                + "remplacera pas à ta place — un pilote se choisit — mais il écarte tout le reste et te laisse "
                + "face à la seule action qui compte, décrite plus bas.</p>",
                "<p><strong>In your case</strong>, the main problem comes from a driver. The assistant will not "
                + "replace it for you — a driver is a choice — but it clears everything else out of the way and leaves "
                + "you facing the single action that matters, described below.</p>"));

        sb.Append("</div>");
    }

    /// <summary>Évolution depuis le scan précédent — la réponse à « est-ce que c'est réparé ? ».</summary>
    private static void ComparisonSection(StringBuilder sb, DiagnosticReport r)
    {
        var c = r.Comparison;
        if (c is null) return;

        sb.Append(Lang.T("<section><h2>Évolution depuis le dernier scan</h2>", "<section><h2>Change since the last scan</h2>"));
        sb.Append($"<div class=\"card {(c.Tone == "ok" ? "okcard" : c.Tone)}\">");
        sb.Append($"<h3>{H(c.Assessment)}</h3>");

        // Les dégradations matérielles se lisent AVANT le détail : ce sont elles qui
        // justifient la couleur de la carte, et les reléguer dans la liste du bas
        // reproduirait le défaut que ce bloc corrige.
        if (c.HardwareConcerns.Count > 0)
        {
            sb.Append("<ul class=\"concerns\">");
            foreach (var h in c.HardwareConcerns.OrderByDescending(x => x.Severity == "crit"))
                sb.Append($"<li class=\"{(h.Severity == "crit" ? "crit" : "warn")}\">{(h.Severity == "crit" ? "🛑" : "⚠️")} {H(h.Message)}</li>");
            sb.Append("</ul>");
        }

        var items = new List<string>();
        items.Add(c.NewBsodCount == 0
            ? Lang.T("✅ Aucun nouveau crash système", "✅ No new system crash")
            : Lang.T($"❌ {c.NewBsodCount} nouveau(x) crash(s) : {H(string.Join(" · ", c.NewBsods))}", $"❌ {c.NewBsodCount} new crash(es): {H(string.Join(" · ", c.NewBsods))}"));
        if (c.NewWheaEvents > 0) items.Add(Lang.T($"⚠️ {c.NewWheaEvents} nouvelle(s) erreur(s) matérielle(s) WHEA", $"⚠️ {c.NewWheaEvents} new WHEA hardware error(s)"));
        if (c.NewDiskErrorEvents > 0) items.Add(Lang.T($"⚠️ {c.NewDiskErrorEvents} nouvelle(s) erreur(s) disque", $"⚠️ {c.NewDiskErrorEvents} new disk error(s)"));
        if (c.DriverUpdates.Count > 0) items.Add(Lang.T($"🔄 Pilotes mis à jour : {H(string.Join(" · ", c.DriverUpdates))}", $"🔄 Drivers updated: {H(string.Join(" · ", c.DriverUpdates))}"));
        if (c.DiskChanges.Count > 0) items.Add(Lang.T($"💽 Disques : {H(string.Join(" · ", c.DiskChanges))}", $"💽 Drives: {H(string.Join(" · ", c.DiskChanges))}"));
        if (!string.IsNullOrEmpty(c.MemoryTrend)) items.Add($"🧠 {H(c.MemoryTrend)}");

        sb.Append("<p>").Append(string.Join("<br>", items)).Append("</p>");
        sb.Append("</div></section>");
    }

    private static void Findings(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append(Lang.T("<section><h2>Conclusions du diagnostic</h2>", "<section><h2>Diagnostic findings</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Ce que FaultTracePC a trouvé, classé du plus grave au moins grave. Chaque carte explique le problème en clair et dit quoi faire. "
            + "Le niveau de confiance est honnête : « faible » signale une piste à vérifier, pas une certitude.</p>",
            "<p class=\"explain\">What FaultTracePC found, ordered from most to least serious. Each card explains the problem in plain words and says what to do. "
            + "The confidence level is honest: “low” marks a lead to check, not a certainty.</p>"));
        // Tout le critique reste visible ; le reste se replie quand il y en a assez
        // pour que cacher aide plus que gêner. Voir Analysis.FindingDisplay.
        var split = Analysis.FindingDisplay.Split(r.Findings);
        foreach (var f in split.Visibles) FindingCard(sb, f);

        if (split.Repliees.Count > 0)
        {
            sb.Append("<details class=\"fold\"><summary>")
              .Append(H(Analysis.FindingDisplay.FoldLabel(split.Repliees)))
              .Append("</summary>");
            foreach (var f in split.Repliees) FindingCard(sb, f);
            sb.Append("</details>");
        }
        sb.Append("</section>");
    }

    /// <summary>
    /// Une carte de conclusion. Extraite de la boucle parce qu'elle est rendue à
    /// deux endroits désormais : dans la liste visible et dans le bloc replié.
    /// </summary>
    private static void FindingCard(StringBuilder sb, Finding f)
    {
            var (cls, label) = f.Severity switch
            {
                Severity.Critical => ("crit", Lang.T("Critique", "Critical")),
                Severity.Warning => ("warn", Lang.T("Avertissement", "Warning")),
                _ => ("info", Lang.T("Information", "Information")),
            };
            var conf = f.Confidence switch
            {
                Confidence.High => Lang.T("confiance élevée", "high confidence"),
                Confidence.Medium => Lang.T("confiance moyenne", "medium confidence"),
                _ => Lang.T("confiance faible", "low confidence"),
            };
            sb.Append($"<div class=\"card {cls}\"><div class=\"card-head\"><span class=\"badge {cls}\">{label}</span>");
            sb.Append($"<span class=\"conf\">{CategoryLabel(f.Category)} · {conf}</span></div>");
            sb.Append($"<h3>{H(f.Title)}</h3><p>{H(f.Details)}</p>");
            if (!string.IsNullOrEmpty(f.Recommendation))
                // « Recommandation » et « Recommendation » ne diffèrent que d'une
                // lettre : aucun des trois signaux du test de traduction ne pouvait
                // voir cette fuite — ni accent, ni trois mots outils, ni espace avant
                // une ponctuation. Elle a vécu dans le rapport anglais jusqu'en 1.4.
                sb.Append("<p class=\"reco\"><span class=\"recolabel\">")
                  .Append(Lang.T("💡 Recommandation", "💡 Recommendation"))
                  .Append($"</span> {H(f.Recommendation)}</p>");

            // Le rapport conseillait des actions sans jamais dire qu'un bouton les
            // exécute : le mot « Outils » n'apparaissait nulle part. Un lecteur qui
            // ne connaît pas déjà le logiciel n'avait aucun moyen de faire le lien.
            if (ToolboxHint(f.Category) is { } hint)
                sb.Append(Lang.T($"<p class=\"toolhint\"><span class=\"toollabel\">🧰 Dans FaultTracePC</span> bouton <strong>🧰 Outils</strong>, puis : {H(hint)}</p>", $"<p class=\"toolhint\"><span class=\"toollabel\">🧰 In FaultTracePC</span> button <strong>🧰 Tools</strong>, then: {H(hint)}</p>"));
            sb.Append("</div>");
    }

    /// <summary>
    /// Bouton de la boîte à outils correspondant à une catégorie de problème.
    ///
    /// Les libellés sont recopiés à l'identique de ceux de la fenêtre Outils : un
    /// intitulé approximatif ferait chercher un bouton qui n'existe pas, ce qui est
    /// pire que de ne rien indiquer.
    ///
    /// null pour les catégories qu'aucun outil ne traite — alimentation, matériel
    /// physique. Promettre une réparation logicielle là où il faut ouvrir la machine
    /// serait exactement le remède imaginaire que ce logiciel refuse de proposer.
    /// </summary>
    private static string? ToolboxHint(FaultCategory category) => category switch
    {
        FaultCategory.Storage => Lang.T(
            "« 💽 Vérifier le disque système (lecture seule) », puis « 🌡 Santé des disques (SMART) ». "
            + "En cas de réinitialisations de contrôleur, « 🔌 Alimentation des liens ». "
            + "« 💾 Gestion des disques » permet d'identifier un périphérique inconnu.",
            "“💽 Check the system drive (read-only)”, then “🌡 Drive health (SMART)”. "
            + "For controller resets, “🔌 Link power management”. "
            + "“💾 Disk Management” helps identify an unknown device."),
        FaultCategory.Memory => Lang.T("« 🧠 Diagnostic mémoire Windows (redémarre !) ».",
                                       "“🧠 Windows Memory Diagnostic (reboots!)”."),
        FaultCategory.Driver or FaultCategory.GpuDriver => Lang.T(
            "« ⬇ Rechercher et installer les mises à jour (optionnelles et pilotes inclus) » — c'est là que se trouvent les pilotes que la page Paramètres masque.",
            "“⬇ Find and install updates (optional and driver updates included)” — that is where the drivers hidden by the Settings page live."),
        FaultCategory.WindowsUpdate => Lang.T(
            "« 🗑 Désinstaller la mise à jour sélectionnée » si une mise à jour est en cause, ou « ♻ Réinitialiser les composants Windows Update » si les installations échouent.",
            "“🗑 Uninstall the selected update” if an update is to blame, or “♻ Reset the Windows Update components” if installations keep failing."),
        FaultCategory.Software => Lang.T("« 🧪 sfc /scannow (fichiers système) », puis « 🔍 DISM — vérifier l'image Windows ».",
                                         "“🧪 sfc /scannow (system files)”, then “🔍 DISM — check the Windows image”."),
        _ => null,
    };

    /// <summary>Carte « Aide à la réparation » : chemin du script + bouton de téléchargement (Blob).</summary>
    private static void RepairSection(StringBuilder sb, DiagnosticReport r)
    {
        if (r.RepairScriptPath is null) return;

        sb.Append(Lang.T("<section><h2>🛠️ Aide à la réparation</h2><div class=\"repair\">", "<section><h2>🛠️ Repair assistance</h2><div class=\"repair\">"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Une série de tests et de réparations <strong>adaptée aux problèmes trouvés ci-dessus</strong> a été préparée pour cette machine. "
            + "Rien n'est modifié sans te demander : à chaque proposition, tu réponds O (oui) ou N (non).</p>",
            "<p class=\"explain\">A set of checks and repairs <strong>matched to the problems found above</strong> has been prepared for this machine. "
            + "Nothing is changed without asking you: at each step you answer O (yes) or N (no).</p>"));
        if (r.RepairLauncherPath is not null)
        {
            sb.Append(Lang.T(
                "<p class=\"bigstep\"><strong>Pour la lancer :</strong> double-clique sur le fichier "
                + $"<code>{H(Path.GetFileName(r.RepairLauncherPath))}</code> dans ton dossier <code>Documents\\FaultTracePC</code>, "
                + "et accepte la demande d'autorisation de Windows. C'est tout.",
                "<p class=\"bigstep\"><strong>To run it:</strong> double-click the file "
                + $"<code>{H(Path.GetFileName(r.RepairLauncherPath))}</code> in your <code>Documents\\FaultTracePC</code> folder, "
                + "and accept the Windows permission prompt. That is all.") + "</p>");
            sb.Append(Lang.T("<p class=\"small\">Ou clique sur le bouton « 🛠 Lancer la réparation » dans FaultTracePC après un scan — même résultat.</p>", "<p class=\"small\">Or click the “🛠 Run the repair” button in FaultTracePC after a scan — same result.</p>"));
        }
        sb.Append(Lang.T("<details><summary>Options avancées (technicien)</summary>", "<details><summary>Advanced options (technician)</summary>"));
        sb.Append(Lang.T($"<p class=\"small\">Script PowerShell : <code>{H(r.RepairScriptPath)}</code> — exécutable depuis un terminal administrateur :</p>", $"<p class=\"small\">PowerShell script: <code>{H(r.RepairScriptPath)}</code> — runnable from an administrator terminal:</p>"));
        sb.Append($"<pre>powershell -ExecutionPolicy Bypass -File \"{H(r.RepairScriptPath)}\"</pre>");
        sb.Append(Lang.T("<button class=\"btn\" onclick=\"downloadRepair()\">💾 Retélécharger le script (.ps1)</button>", "<button class=\"btn\" onclick=\"downloadRepair()\">💾 Download the script again (.ps1)</button>"));
        sb.Append(Lang.T("<p class=\"small\">Le journal complet de chaque exécution est conservé dans <code>Documents\\FaultTracePC</code>.</p>", "<p class=\"small\">The full log of every run is kept in <code>Documents\\FaultTracePC</code>.</p>"));
        sb.Append("</details></div>");
        // Contenu du script embarqué pour le bouton de téléchargement (échappé en JSON).
        sb.Append("<script>const REPAIR_PS1 = ")
          .Append(System.Text.Json.JsonSerializer.Serialize(RepairScriptGenerator.Generate(r)))
          .Append(";\nfunction downloadRepair(){const b=new Blob([\"\\uFEFF\"+REPAIR_PS1],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='")
          .Append(H(Path.GetFileName(r.RepairScriptPath)))
          .Append("';a.click();URL.revokeObjectURL(a.href);}</script>");
        sb.Append("</section>");
    }

    /// <summary>Processus en cours au moment du scan : RAM, CPU, débit disque.</summary>
    private static void ProcessesSection(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append(Lang.T("<section class=\"tech\"><h2>Processus en cours au moment du scan</h2>", "<section class=\"tech\"><h2>Running processes at scan time</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">La liste des programmes qui tournaient pendant le scan, et ce qu'ils consommaient. "
            + "Utile pour repérer un programme qui monopolise la mémoire ou le processeur.</p>",
            "<p class=\"explain\">The list of programs that were running during the scan, and what they were using. "
            + "Useful for spotting a program that is hogging the memory or the processor.</p>"));
        if (r.Processes.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Relevé des processus indisponible.</p></section>", "<p class=\"empty\">Process readings unavailable.</p></section>")); return; }

        var os = r.System.Os;
        if (os.TotalVisibleMemoryKB > 0)
        {
            var physUsed = 100.0 * (os.TotalVisibleMemoryKB - os.FreePhysicalMemoryKB) / os.TotalVisibleMemoryKB;
            var commitUsed = os.TotalVirtualMemoryKB > 0
                ? 100.0 * (os.TotalVirtualMemoryKB - os.FreeVirtualMemoryKB) / os.TotalVirtualMemoryKB : 0;
            sb.Append(Lang.T($"<p class=\"sub2\">Mémoire physique utilisée : <strong>{physUsed:0} %</strong> ({RulesEngine.FormatBytes((os.TotalVisibleMemoryKB - os.FreePhysicalMemoryKB) * 1024)} / {RulesEngine.FormatBytes(os.TotalVisibleMemoryKB * 1024)})", $"<p class=\"sub2\">Physical memory in use: <strong>{physUsed:0}%</strong> ({RulesEngine.FormatBytes((os.TotalVisibleMemoryKB - os.FreePhysicalMemoryKB) * 1024)} / {RulesEngine.FormatBytes(os.TotalVisibleMemoryKB * 1024)})"));
            if (commitUsed > 0)
                sb.Append(Lang.T($" · Mémoire virtuelle engagée (RAM + fichier d'échange) : <strong>{commitUsed:0} %</strong>", $" · Virtual memory committed (RAM + page file): <strong>{commitUsed:0}%</strong>"));
            sb.Append(Lang.T(". CPU et débit disque mesurés sur ~1 s. Ce relevé montre l'état <em>au moment du scan</em> — pour l'état au moment d'un crash passé, voir les événements « Saturation mémoire » ci-dessous ou le futur mode surveillance (Phase 3).</p>", ". CPU and disk throughput measured over ~1 s. This reading shows the state <em>at scan time</em> — for the state during a past crash, see the “Memory exhaustion” events below or the flight recorder.</p>"));
        }

        sb.Append(Lang.T("<table><thead><tr><th>Processus</th><th>PID</th><th>RAM privée</th><th>Working set</th><th>CPU %</th><th>Disque (o/s)</th></tr></thead><tbody>", "<table><thead><tr><th>Process</th><th>PID</th><th>Private RAM</th><th>Working set</th><th>CPU %</th><th>Disk (B/s)</th></tr></thead><tbody>"));
        var top = r.Processes.Take(25).ToList();
        // On ajoute aussi les gros consommateurs CPU absents du top RAM.
        top.AddRange(r.Processes.OrderByDescending(p => p.CpuPercent).Take(8).Where(p => !top.Contains(p)));
        foreach (var p in top)
        {
            var hot = p.PrivateBytes > 2L * 1024 * 1024 * 1024 || p.CpuPercent >= 25;
            sb.Append($"<tr{(hot ? " class=\"oldrow\"" : "")}><td>{H(p.Name)}</td><td class=\"mono\">{p.Pid}</td>");
            sb.Append($"<td>{RulesEngine.FormatBytes((ulong)Math.Max(0, p.PrivateBytes))}</td><td>{RulesEngine.FormatBytes((ulong)Math.Max(0, p.WorkingSetBytes))}</td>");
            sb.Append($"<td>{p.CpuPercent:0.#}</td><td>{(p.IoBytesPerSec > 0 ? RulesEngine.FormatBytes((ulong)p.IoBytesPerSec) + "/s" : "—")}</td></tr>");
        }
        sb.Append("</tbody></table>");
        sb.Append(Lang.T($"<p class=\"empty\">{r.Processes.Count} processus au total — affichés : les 25 plus gros en RAM + les plus actifs en CPU. Lignes surlignées : &gt; 2 Go de RAM privée ou ≥ 25 % CPU.</p>", $"<p class=\"empty\">{r.Processes.Count} processes in total — shown: the 25 largest by RAM plus the most CPU-active. Highlighted rows use more than 2 GB or 25% CPU.</p>"));
        sb.Append("</section>");
    }

    /// <summary>La boîte noire : état du service et dernières secondes avant chaque crash.</summary>
    private static void FlightSection(StringBuilder sb, DiagnosticReport r)
    {
        var f = r.Flight;
        // Section visible en mode simple uniquement quand elle a du contenu utile.
        var techClass = f.Contexts.Count > 0 || f.Alerts.Count > 0 ? "" : " class=\"tech\"";
        sb.Append(Lang.T($"<section{techClass}><h2>📡 Boîte noire (surveillance temps réel)</h2>", $"<section{techClass}><h2>📡 Flight recorder (real-time monitoring)</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Le service de surveillance enregistre en continu températures, mémoire et processus. "
            + Lang.T("En cas de crash, on retrouve ici les dernières secondes AVANT la panne — ce qu'aucune analyse après coup ne peut reconstituer.</p>", "none"),
            "<p class=\"explain\">The monitoring service continuously records temperatures, memory and processes. "
            + "After a crash, the last seconds BEFORE the failure are found here — something no post-mortem analysis can reconstruct.</p>"));

        if (!f.JournalFound)
        {
            sb.Append(Lang.T("<p class=\"empty\">Aucun journal de surveillance sur cette machine. Active la surveillance avec le bouton « 📡 Surveillance temps réel » de FaultTracePC — le service s'installe en un clic et consomme moins de 1 % de CPU.</p></section>", "<p class=\"empty\">No monitoring log on this machine. Turn monitoring on with the “📡 Real-time monitoring” button in FaultTracePC — the service installs in one click and uses less than 1% CPU.</p></section>"));
            return;
        }

        if (f.Alerts.Count > 0)
        {
            sb.Append(Lang.T("<h4 class=\"ctxtitle\">Alertes préventives émises en temps réel</h4>", "<h4 class=\"ctxtitle\">Preventive alerts raised live</h4>"));
            sb.Append(Lang.T("<table><thead><tr><th>Date</th><th>Niveau</th><th>Alerte</th><th>Que faire</th></tr></thead><tbody>", "<table><thead><tr><th>Date</th><th>Level</th><th>Alert</th><th>What to do</th></tr></thead><tbody>"));
            foreach (var a in f.Alerts.Take(40))
            {
                var badge = a.Level == "crit" ? Lang.T("<span class=\"badge crit\">Critique</span>", "<span class=\"badge crit\">Critical</span>") : Lang.T("<span class=\"badge warn\">Alerte</span>", "<span class=\"badge warn\">Warning</span>");
                sb.Append($"<tr><td>{Lang.ShortDateMinute(a.Time)}</td><td>{badge}</td><td>{H(a.Title)}</td><td class=\"small\">{H(a.Recommendation)}</td></tr>");
            }
            sb.Append("</tbody></table>");
        }

        if (f.Thermal.Count > 0)
        {
            sb.Append(Lang.T("<h4 class=\"ctxtitle\">Températures dans la durée</h4>", "<h4 class=\"ctxtitle\">Temperatures over time</h4>"));
            sb.Append(Lang.T(
                "<p class=\"explain\">Ce qui annonce un plantage thermique n'est pas la température d'un instant — une pointe "
                + "pendant un jeu ou une compilation est normale — mais le TEMPS CUMULÉ passé trop haut. "
                + "Les durées ci-dessous ne comptent que les périodes réellement mesurées : machine éteinte ou service arrêté, rien n'est compté.</p>",
                "<p class=\"explain\">What announces a thermal shutdown is not the temperature at one instant — a spike "
                + "during a game or a compile is normal — but the ACCUMULATED TIME spent too high. "
                + "The durations below count only the periods actually measured: machine off or service stopped, nothing is counted.</p>"));
            sb.Append(Lang.T(
                "<table><thead><tr><th>Capteur</th><th>Maximum</th><th>Moyenne</th>"
                + "<th>Au-dessus du seuil d'alerte</th><th>Au-dessus du seuil critique</th><th>Durée mesurée</th></tr></thead><tbody>",
                "<table><thead><tr><th>Sensor</th><th>Maximum</th><th>Average</th>"
                + "<th>Above the warning threshold</th><th>Above the critical threshold</th><th>Time measured</th></tr></thead><tbody>"));
            foreach (var t in f.Thermal)
            {
                bool bad = t.AboveCrit >= TimeSpan.FromMinutes(5);
                bool warn = !bad && (t.AboveWarn >= TimeSpan.FromMinutes(30) || t.WarnPercent >= 20);
                sb.Append($"<tr{(bad || warn ? " class=\"oldrow\"" : "")}><td>{H(t.Sensor)}</td>");
                sb.Append($"<td>{(t.MaxC is { } m ? $"{m:0.#} °C" : "—")}"
                        + (t.MaxAt is { } at ? $" <span class=\"small\">({Lang.ShortDateMinute(at)})</span>" : "") + "</td>");
                sb.Append($"<td>{(t.AverageC is { } a2 ? $"{a2:0.#} °C" : "—")}</td>");
                sb.Append(Lang.T(
                    $"<td>{(t.AboveWarn > TimeSpan.Zero ? $"<strong>{Analysis.ThermalHistory.Humanize(t.AboveWarn)}</strong> <span class=\"small\">({t.WarnPercent:0.#} % · seuil {t.WarnThreshold:0} °C)</span>" : $"aucun <span class=\"small\">(seuil {t.WarnThreshold:0} °C)</span>")}</td>",
                    $"<td>{(t.AboveWarn > TimeSpan.Zero ? $"<strong>{Analysis.ThermalHistory.Humanize(t.AboveWarn)}</strong> <span class=\"small\">({t.WarnPercent.ToString("0.#", Lang.Culture)}% · threshold {t.WarnThreshold:0} °C)</span>" : $"none <span class=\"small\">(threshold {t.WarnThreshold:0} °C)</span>")}</td>"));
                sb.Append(Lang.T(
                    $"<td>{(t.AboveCrit > TimeSpan.Zero ? $"<strong>{Analysis.ThermalHistory.Humanize(t.AboveCrit)}</strong> <span class=\"small\">(seuil {t.CritThreshold:0} °C)</span>" : $"aucun <span class=\"small\">(seuil {t.CritThreshold:0} °C)</span>")}</td>",
                    $"<td>{(t.AboveCrit > TimeSpan.Zero ? $"<strong>{Analysis.ThermalHistory.Humanize(t.AboveCrit)}</strong> <span class=\"small\">(threshold {t.CritThreshold:0} °C)</span>" : $"none <span class=\"small\">(threshold {t.CritThreshold:0} °C)</span>")}</td>"));
                sb.Append($"<td class=\"small\">{Analysis.ThermalHistory.Humanize(t.Observed)}</td></tr>");

                foreach (var ep in t.LongestEpisodes)
                    sb.Append(Lang.T(
                        $"<tr><td colspan=\"6\" class=\"small\">↳ épisode continu de {ep.Minutes:0.#} min "
                        + $"le {ep.Start:dd/MM à HH:mm}, pointe à {ep.PeakC:0.#} °C</td></tr>",
                        $"<tr><td colspan=\"6\" class=\"small\">↳ continuous episode of {ep.Minutes.ToString("0.#", Lang.Culture)} min "
                        + $"on {ep.Start:MM-dd HH:mm}, peaking at {ep.PeakC.ToString("0.#", Lang.Culture)} °C</td></tr>"));
            }
            sb.Append("</tbody></table>");
            sb.Append(Lang.T("<p class=\"empty\">Les seuils sont modifiables dans ", "<p class=\"empty\">The thresholds can be changed in ")
                    + "<code>ProgramData\\FaultTracePC\\alerts.json</code> "
                    + "(<code>CpuTempWarn</code>, <code>CpuTempCrit</code>, <code>GpuTempWarn</code>, <code>GpuTempCrit</code>).</p>");
        }

        sb.Append(Lang.T($"<p class=\"sub2\">État : <strong>{(f.Active ? "🟢 service actif" : "🔴 service arrêté")}</strong>",
                         $"<p class=\"sub2\">State: <strong>{(f.Active ? "🟢 service running" : "🔴 service stopped")}</strong>")
                + (f.LastSampleTime is { } last
                    ? Lang.T($" · dernier relevé : {last:dd/MM/yyyy HH:mm:ss}", $" · last reading: {last:yyyy-MM-dd HH:mm:ss}") : "")
                + Lang.T($" · {f.DaysCovered} jour(s) de journal", $" · {f.DaysCovered} day(s) of log")
                + (f.AbruptSessionEnds > 0
                    ? Lang.T($" · <strong>{f.AbruptSessionEnds} arrêt(s) brutal(aux) détecté(s)</strong>",
                             $" · <strong>{f.AbruptSessionEnds} abrupt shutdown(s) detected</strong>") : "")
                + "</p>");

        foreach (var ctx in f.Contexts.Take(6))
        {
            sb.Append(Lang.T($"<h4 class=\"ctxtitle\">Dernières secondes avant l'incident du {ctx.CrashTime:dd/MM/yyyy HH:mm}</h4>", $"<h4 class=\"ctxtitle\">Last seconds before the incident of {ctx.CrashTime:yyyy-MM-dd HH:mm}</h4>"));
            sb.Append(Lang.T("<table><thead><tr><th>Heure</th><th>CPU %</th><th>Temp. CPU</th><th>Temp. GPU</th><th>RAM %</th><th>Mém. virtuelle %</th><th>Plus gros processus</th></tr></thead><tbody>", "<table><thead><tr><th>Time</th><th>CPU %</th><th>CPU temp.</th><th>GPU temp.</th><th>RAM %</th><th>Virtual mem. %</th><th>Largest processes</th></tr></thead><tbody>"));
            foreach (var s in ctx.Samples)
            {
                sb.Append($"<tr><td>{s.Time:HH:mm:ss}</td><td>{Fmt(s.CpuLoad)}</td><td>{Fmt(s.CpuTemp, " °C")}</td>");
                sb.Append($"<td>{Fmt(s.GpuTemp, " °C")}</td><td>{Fmt(s.MemPct)}</td><td>{Fmt(s.CommitPct)}</td>");
                sb.Append($"<td class=\"small\">{H(s.TopProcesses ?? "")}</td></tr>");
            }
            sb.Append("</tbody></table>");
        }
        if (f.Contexts.Count == 0)
            sb.Append(Lang.T("<p class=\"empty\">Aucun crash pendant la période couverte par le journal — la boîte noire veille.</p>", "<p class=\"empty\">No crash during the period covered by the log — the flight recorder is watching.</p>"));
        sb.Append("</section>");
    }

    private static string Fmt(double? v, string suffix = "") =>
        v is null ? "—" : $"{v:0.#}{suffix}";

    private static void BsodSection(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append(Lang.T("<section class=\"tech\"><h2>Écrans bleus (BSOD)</h2>", "<section class=\"tech\"><h2>Blue screens (BSOD)</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Un « écran bleu » signifie que Windows s'est arrêté d'urgence pour éviter d'endommager le système. "
            + "Chaque ligne est un arrêt de ce type ; la colonne « Pilote suspect » désigne le composant le plus probablement responsable.",
            "<p class=\"explain\">A “blue screen” means Windows stopped in an emergency to avoid damaging the system. "
            + "Each row is one such stop; the “Suspect driver” column names the component most likely responsible.") + "</p>");
        if (r.Bsods.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Aucun BSOD détecté sur la période.</p></section>", "<p class=\"empty\">No BSOD detected over the period.</p></section>")); return; }

        sb.Append(Lang.T("<table><thead><tr><th>Date</th><th>Bug Check</th><th>Nom</th><th>Paramètres</th><th>Pilote suspect</th><th>Dump</th><th>Sources</th></tr></thead><tbody>", "<table><thead><tr><th>Date</th><th>Bug Check</th><th>Name</th><th>Parameters</th><th>Suspect driver</th><th>Dump</th><th>Sources</th></tr></thead><tbody>"));
        foreach (var b in r.Bsods)
        {
            var code = b.BugCheckCode is null ? "—" : $"0x{b.BugCheckCode:X8}";
            var pars = b.Parameters is null ? "—" : string.Join("<br>", b.Parameters.Select(p => $"0x{p:X16}"));
            sb.Append($"<tr><td>{Lang.DateMinute(b.TimeLocal)}</td><td class=\"mono\">{code}</td><td>{H(b.BugCheckName)}</td>");
            var driverCell = b.SuspectDriver is null
                ? Lang.T("<span class=\"small\">non identifié (installer WinDbg pour l'analyse symbolique)</span>", "<span class=\"small\">not identified (install WinDbg for symbolic analysis)</span>")
                : $"<strong>{H(b.SuspectDriver)}</strong>";
            sb.Append($"<td class=\"mono small\">{pars}</td><td>{driverCell}</td>");
            sb.Append($"<td class=\"small\">{H(b.DumpPath is null ? "—" : Path.GetFileName(b.DumpPath))}</td><td class=\"small\">{H(string.Join(", ", b.Sources))}</td></tr>");
        }
        sb.Append("</tbody></table></section>");
    }

    private static void DumpSection(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append(Lang.T("<section class=\"tech\"><h2>Fichiers dump présents</h2>", "<section class=\"tech\"><h2>Dump files present</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Un « dump » est la boîte noire que Windows enregistre au moment d'un crash. "
            + "FaultTracePC les a lus (et analysés avec WinDbg si disponible) pour identifier le coupable.",
            "<p class=\"explain\">A “dump” is the black box Windows writes at the moment of a crash. "
            + "FaultTracePC has read them (and analysed them with WinDbg where available) to identify the culprit.") + "</p>");
        if (r.Dumps.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Aucun fichier dump trouvé (Minidump, MEMORY.DMP, LiveKernelReports).</p></section>", "<p class=\"empty\">No dump file found (Minidump, MEMORY.DMP, LiveKernelReports).</p></section>")); return; }

        sb.Append(Lang.T("<table><thead><tr><th>Fichier</th><th>Type</th><th>Date</th><th>Taille</th><th>Code STOP (en-tête)</th><th>Analyse symbolique (WinDbg)</th></tr></thead><tbody>", "<table><thead><tr><th>File</th><th>Type</th><th>Date</th><th>Size</th><th>STOP code (header)</th><th>Symbolic analysis (WinDbg)</th></tr></thead><tbody>"));
        foreach (var d in r.Dumps)
        {
            var kind = d.Kind switch
            {
                DumpKind.KernelMinidump => Lang.T("Minidump noyau", "Kernel minidump"),
                DumpKind.FullMemoryDump => Lang.T("Dump mémoire complet", "Complete memory dump"),
                DumpKind.LiveKernelReport => "Live Kernel Report",
                DumpKind.UserModeMinidump => Lang.T("Dump applicatif (WER)", "Application dump (WER)"),
                _ => Lang.T("Inconnu", "Unknown"),
            };
            var code = d.BugCheckCode is null
                ? (d.ParseError is null ? "—" : Lang.T($"illisible ({H(d.ParseError)})", $"unreadable ({H(d.ParseError)})"))
                : $"0x{d.BugCheckCode:X8} {H(BugCheckCatalog.NameOf(d.BugCheckCode.Value))}";

            string analysis;
            if (d.DeepAnalyzed && d.FaultingModule is not null)
            {
                analysis = $"<strong>{H(d.FaultingModule)}</strong>";
                if (d.CrashProcessName is not null) analysis += Lang.T($"<br><span class=\"small\">processus : {H(d.CrashProcessName)}</span>", $"process: {H(d.CrashProcessName)}");
                if (d.FailureBucket is not null) analysis += $"<br><span class=\"small\">{H(d.FailureBucket)}</span>";
                if (d.StackExcerpt is not null)
                    analysis += Lang.T($"<details><summary class=\"small\">pile d'appels</summary><pre class=\"stack\">{H(d.StackExcerpt)}</pre></details>", $"<details><summary class=\"small\">call stack</summary><pre class=\"stack\">{H(d.StackExcerpt)}</pre></details>");
            }
            else if (d.DeepAnalysisError is not null)
                analysis = Lang.T($"<span class=\"small\">échec : {H(d.DeepAnalysisError)}</span>", $"failed: {H(d.DeepAnalysisError)}");
            else if (d.Kind is DumpKind.KernelMinidump or DumpKind.FullMemoryDump)
                analysis = Lang.T("<span class=\"small\">non analysé</span>", "<span class=\"small\">not analysed</span>");
            else
                analysis = "—";

            sb.Append($"<tr><td class=\"small\">{H(d.Path)}</td><td>{kind}</td><td>{Lang.DateMinute(d.CrashTimeFromHeader ?? d.LastWriteTime)}</td>");
            sb.Append($"<td>{RulesEngine.FormatBytes((ulong)d.SizeBytes)}</td><td class=\"mono small\">{code}</td><td>{analysis}</td></tr>");
        }
        sb.Append("</tbody></table></section>");
    }

    private static void EventsSection(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append(Lang.T("<section class=\"tech\"><h2>Historique des événements significatifs</h2>", "<section class=\"tech\"><h2>History of significant events</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Le journal de bord de Windows : chaque ligne est un incident que le système a enregistré "
            + "(erreur, crash, redémarrage…). C'est la matière première du diagnostic.",
            "<p class=\"explain\">The Windows logbook: each row is an incident the system recorded "
            + "(error, crash, restart…). It is the raw material of the diagnosis.") + "</p>");
        if (r.Events.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Aucun événement significatif sur la période.</p></section>", "<p class=\"empty\">No significant event over the period.</p></section>")); return; }

        // Résumé par catégorie : chaque puce est un BOUTON de filtre.
        sb.Append(Lang.T("<p class=\"sub2\">Clique sur une catégorie pour filtrer le tableau ; « Tous » réaffiche tout.</p>", "<p class=\"sub2\">Click a category to filter the table; “All” shows everything again.</p>"));
        sb.Append("<div class=\"chips\" id=\"evt-chips\">");
        sb.Append(Lang.T($"<button type=\"button\" class=\"chip active\" data-cat=\"all\">Tous : <strong>{r.Events.Count}</strong></button>", $"<button type=\"button\" class=\"chip active\" data-cat=\"all\">All: <strong>{r.Events.Count}</strong></button>"));
        foreach (var g in r.Events.GroupBy(e => e.Category).OrderByDescending(g => g.Count()))
            sb.Append(Lang.T($"<button type=\"button\" class=\"chip\" data-cat=\"{g.Key}\">{CategoryEventLabel(g.Key)} : <strong>{g.Count()}</strong></button>",
                             $"<button type=\"button\" class=\"chip\" data-cat=\"{g.Key}\">{CategoryEventLabel(g.Key)}: <strong>{g.Count()}</strong></button>"));
        sb.Append("</div>");

        const int maxRows = 400;
        sb.Append(Lang.T("<table id=\"evt-table\"><thead><tr><th>Date</th><th>Catégorie</th><th>Source</th><th>ID</th><th>Détail</th></tr></thead><tbody>", "<table id=\"evt-table\"><thead><tr><th>Date</th><th>Category</th><th>Source</th><th>ID</th><th>Detail</th></tr></thead><tbody>"));
        foreach (var e in r.Events.Take(maxRows))
        {
            var extra = e.Extracted.Count > 0
                ? " <span class=\"extract\">" + H(string.Join(" · ", e.Extracted.Where(kv => kv.Key != "HasErrors").Select(kv => $"{kv.Key}: {kv.Value}"))) + "</span>"
                : "";
            sb.Append($"<tr data-cat=\"{e.Category}\"><td>{Lang.ShortDateMinute(e.TimeLocal)}</td><td>{CategoryEventLabel(e.Category)}</td><td class=\"small\">{H(e.Provider)}</td>");
            sb.Append($"<td>{e.EventId}</td><td class=\"small\">{H(Shorten(e.Message, 180))}{extra}</td></tr>");
        }
        sb.Append("</tbody></table>");
        sb.Append(Lang.T("<p class=\"empty\" id=\"evt-none\" style=\"display:none\">Aucun événement de cette catégorie parmi les lignes affichées.</p>", "<p class=\"empty\" id=\"evt-none\" style=\"display:none\">No event of this category among the rows shown.</p>"));
        if (r.Events.Count > maxRows)
            sb.Append(Lang.T($"<p class=\"empty\">… {r.Events.Count - maxRows} événements supplémentaires non affichés (les plus récents sont listés).</p>", $"<p class=\"empty\">… {r.Events.Count - maxRows} further events not shown (the most recent ones are listed).</p>"));
        sb.Append("</section>");
    }

    private static void SystemSection(StringBuilder sb, DiagnosticReport r)
    {
        var s = r.System;
        sb.Append(Lang.T("<section class=\"tech\"><h2>Configuration système</h2>", "<section class=\"tech\"><h2>System configuration</h2>"));
        sb.Append(Lang.T("<p class=\"explain\">La fiche d'identité de la machine — utile à communiquer si tu demandes de l'aide à un technicien.</p>", "<p class=\"explain\">The machine's identity card — useful to pass on if you ask a technician for help.</p>"));
        sb.Append("<div class=\"grid\">");

        Card(sb, "Windows", $"{H(s.Os.Caption)} {H(s.Os.DisplayVersion)}<br>Build {H(s.Os.BuildNumber)} · {H(s.Os.Architecture)}"
            + Lang.T("<br>Installé le ", "<br>Installed on ")
            + (s.Os.InstallDate is { } installe ? Lang.Date(installe) : "—")
            + Lang.T("<br>Dernier démarrage : ", "<br>Last boot: ")
            + (s.Os.LastBootUpTime is { } demarrage ? Lang.DateMinute(demarrage) : "—")
            + (s.Os.Uptime is { } up ? Lang.T($" (allumé depuis {(int)up.TotalHours} h {up.Minutes:00})", $" (up for {(int)up.TotalHours}h{up.Minutes:00})") : ""));

        Card(sb, "Machine / BIOS", $"{H(s.Bios.SystemManufacturer)} {H(s.Bios.SystemModel)}"
            + Lang.T($"<br>Carte mère : {H(s.Bios.BaseboardManufacturer)} {H(s.Bios.BaseboardProduct)}", $"<br>Motherboard: {H(s.Bios.BaseboardManufacturer)} {H(s.Bios.BaseboardProduct)}")
            + $"<br>BIOS {H(s.Bios.Version)} ({(s.Bios.ReleaseDate is { } brd ? Lang.Date(brd) : "—")})");

        Card(sb, Lang.T("Processeur", "Processor"), Lang.T($"{H(s.Cpu.Name)}<br>{s.Cpu.Cores} cœurs / {s.Cpu.LogicalProcessors} threads · {s.Cpu.MaxClockSpeedMHz} MHz", $"{H(s.Cpu.Name)}<br>{s.Cpu.Cores} cores / {s.Cpu.LogicalProcessors} threads · {s.Cpu.MaxClockSpeedMHz} MHz"));

        var ramTotal = s.RamModules.Aggregate(0UL, (acc, m) => acc + m.CapacityBytes);
        Card(sb, Lang.T($"Mémoire ({RulesEngine.FormatBytes(ramTotal)})", $"Memory ({RulesEngine.FormatBytes(ramTotal)})"),
            s.RamModules.Count == 0 ? Lang.T("détail indisponible", "detail unavailable")
            : string.Join("<br>", s.RamModules.Select(m =>
                Lang.T($"{H(m.DeviceLocator)} : {RulesEngine.FormatBytes(m.CapacityBytes)} {H(m.Manufacturer)} {H(m.PartNumber)} @ {(m.ConfiguredSpeedMTs > 0 ? m.ConfiguredSpeedMTs : m.SpeedMTs)} MT/s",
                       $"{H(m.DeviceLocator)}: {RulesEngine.FormatBytes(m.CapacityBytes)} {H(m.Manufacturer)} {H(m.PartNumber)} @ {(m.ConfiguredSpeedMTs > 0 ? m.ConfiguredSpeedMTs : m.SpeedMTs)} MT/s"))));

        Card(sb, Lang.T("Cartes graphiques", "Graphics cards"),
            s.Gpus.Count == 0 ? Lang.T("aucune détectée", "none detected")
            : string.Join("<br>", s.Gpus.Select(g =>
                Lang.T($"{H(g.Name)} — pilote {H(g.DriverVersion)} du ", $"{H(g.Name)} — driver {H(g.DriverVersion)} dated ")
                + (g.DriverDate is { } dateGpu ? Lang.Date(dateGpu) : "—"))));

        Card(sb, Lang.T("Disques physiques", "Physical drives"),
            s.Disks.Count == 0 ? Lang.T("aucun détecté", "none detected")
            : string.Join("<br>", s.Disks.Select(d =>
                // Numéro et lettres d'abord : c'est ce qui permet de reconnaître le
                // disque dans le Gestionnaire de disques et dans l'Explorateur. Le
                // modèle seul ne dit à personne de quel disque il s'agit.
                (d.Index is { } ix ? Lang.T($"<strong>Disque {ix}</strong>", $"<strong>Disk {ix}</strong>") : Lang.T("<strong>Disque</strong>", "<strong>Disk</strong>"))
                // Sans lettre, on n'écrit rien : un disque sans volume monté est
                // normal (disque neuf, non partitionné, ou branché en lecture par un
                // technicien). Afficher « aucune lettre » entre parenthèses donnait
                // l'impression d'un défaut là où il n'y en a pas.
                + (d.Letters.Count > 0 ? $" ({H(string.Join(", ", d.Letters))})" : "")
                + Lang.T($" — {H(d.Model)} ({RulesEngine.FormatBytes(d.SizeBytes)}, {H(string.IsNullOrEmpty(d.MediaType) ? d.InterfaceType : d.MediaType)}) — santé : {H(SanteLisible(d))}",
                         $" — {H(d.Model)} ({RulesEngine.FormatBytes(d.SizeBytes)}, {H(string.IsNullOrEmpty(d.MediaType) ? d.InterfaceType : d.MediaType)}) — health: {H(SanteLisible(d))}")
                + (d.TemperatureC is { } t ? $" · {t} °C" : "")
                + (d.WearPercent is { } w and > 0 ? Lang.T($" · usure {w} %", $" · wear {w}%") : ""))));

        if (s.Batteries.Count > 0)
        {
            Card(sb, Lang.T("Batterie", "Battery"),
                string.Join("<br>", s.Batteries.Select(b =>
                {
                    var health = b.HealthPercent is { } hp
                        ? Lang.T($"<strong>{hp} % de santé</strong> (usure {b.WearPercent} %)", $"<strong>{hp}% health</strong> (wear {b.WearPercent}%)")
                        : Lang.T("usure non mesurable", "wear not measurable");
                    var cap = b.DesignedCapacity is { } dc && b.FullChargedCapacity is { } fc
                        ? Lang.T($"<br>{fc} mWh à pleine charge sur {dc} mWh d'origine", $"<br>{fc} mWh at full charge out of {dc} mWh when new") : "";
                    var cyc = b.CycleCount is { } c and > 0 ? Lang.T($" · {c} cycles", $" · {c} cycles") : "";
                    return $"{H(b.Name)} {H(b.Chemistry)}<br>{health}{cap}{cyc}"
                         + (b.ChargeRemainingPercent is { } ch ? Lang.T($"<br>Charge actuelle : {ch} % ({H(b.Status)})", $"<br>Current charge: {ch}% ({H(b.Status)})") : "");
                })));
        }

        Card(sb, Lang.T("Volumes", "Volumes"),
            s.Volumes.Count == 0 ? Lang.T("aucun", "none")
            : string.Join("<br>", s.Volumes.Select(v =>
                Lang.T($"{H(v.Letter)} {H(v.Label)} ({H(v.FileSystem)}) : {RulesEngine.FormatBytes(v.FreeBytes)} libres / {RulesEngine.FormatBytes(v.SizeBytes)} ({v.PercentFree} %)", $"{H(v.Letter)} {H(v.Label)} ({H(v.FileSystem)}): {RulesEngine.FormatBytes(v.FreeBytes)} free / {RulesEngine.FormatBytes(v.SizeBytes)} ({v.PercentFree}%)"))));

        Card(sb, Lang.T("Fichier d'échange", "Page file"), H(s.Os.PageFileInfo));

        sb.Append("</div></section>");
    }

    /// <summary>Détail SMART : les chiffres qui justifient le verdict sur chaque disque.</summary>
    private static void SmartSection(StringBuilder sb, DiagnosticReport r)
    {
        var disks = r.System.Disks.Where(d => d.Smart is { HasData: true }).ToList();
        if (r.System.Disks.Count == 0) return;

        sb.Append(Lang.T("<section class=\"tech\"><h2>État de santé des disques (SMART)</h2>", "<section class=\"tech\"><h2>Drive health (SMART)</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Les disques tiennent eux-mêmes des compteurs d'incidents. Seuls ceux qui annoncent "
            + "réellement une panne sont repris ici : les secteurs défectueux (le disque s'abîme), les erreurs de "
            + "transmission (le câble est en cause, pas le disque) et l'usure d'un SSD.",
            "<p class=\"explain\">Drives keep their own incident counters. Only those that genuinely announce a failure "
            + "are shown here: bad sectors (the drive is deteriorating), transmission errors (the cable is at fault, "
            + "not the drive) and SSD wear.") + "</p>");

        // Aucune mesure : on le DIT, plutôt que d'afficher un tableau de tirets qui
        // laisserait croire que les disques ont été contrôlés et déclarés sains.
        if (disks.Count == 0)
        {
            bool plusieurs = r.System.Disks.Count > 1;
            sb.Append(Lang.T("<p class=\"empty\"><strong>Aucun compteur n'a pu être lu sur ",
                             "<p class=\"empty\"><strong>No counter could be read on "));
            sb.Append(Lang.T(plusieurs ? "ces disques" : "ce disque", plusieurs ? "these drives" : "this drive"));
            sb.Append(Lang.T(
                " — ce n'est ni un bon ni un mauvais signe : l'état interne n'est tout simplement pas connu.</strong><br>",
                " — this is neither a good nor a bad sign: the internal state is simply not known.</strong><br>"));
            sb.Append(Lang.T(
                "Les attributs SMART bruts ne sont exposés à Windows que par les disques SATA/ATA. Beaucoup de "
                + "contrôleurs NVMe, et la plupart des contrôleurs RAID, ne les transmettent pas — Windows ne peut "
                + "alors rien en dire, et FaultTracePC non plus.<br>",
                "Raw SMART attributes are exposed to Windows only by SATA/ATA drives. Many NVMe controllers, and most "
                + "RAID controllers, do not pass them on — Windows can then say nothing about them, and neither can "
                + "FaultTracePC.<br>"));
            sb.Append(Lang.T("Pour connaître malgré tout l'état de ", "To find out the state of "));
            sb.Append(Lang.T(plusieurs ? "ces disques" : "ce disque", plusieurs ? "these drives" : "this drive"));
            sb.Append(Lang.T(
                " : l'outil du fabricant (Samsung Magician, Crucial Storage Executive, WD Dashboard…) parle "
                + "directement au disque, ou un utilitaire spécialisé comme CrystalDiskInfo.</p>",
                " anyway: the manufacturer's tool (Samsung Magician, Crucial Storage Executive, WD Dashboard…) talks "
                + "to the drive directly, as does a dedicated utility such as CrystalDiskInfo.</p>"));
            foreach (var d in r.System.Disks)
                sb.Append($"<p class=\"small\">{H(d.Model)}{(string.IsNullOrEmpty(d.MediaType) ? "" : $" · {H(d.MediaType)}")}"
                        + $"{(string.IsNullOrEmpty(d.InterfaceType) ? "" : $" · {H(d.InterfaceType)}")}"
                        + Lang.T($"{(d.Health == DiskHealth.NotReported ? "" : $" · état déclaré par Windows : {H(d.Health.Label())}")}</p>", $" · state reported by Windows: {H(d.Health.Label())}"));
            sb.Append("</section>");
            return;
        }
        sb.Append(Lang.T("<table><thead><tr><th>Disque</th><th>Secteurs réalloués</th><th>Secteurs en attente</th>", "<table><thead><tr><th>Drive</th><th>Reallocated sectors</th><th>Pending sectors</th>")
                + Lang.T("<th>Illisibles / erreurs d'intégrité</th><th>Erreurs CRC (câble)</th><th>Réserve (NVMe)</th>", "<th>Unreadable / integrity errors</th><th>CRC errors (cable)</th><th>Spare (NVMe)</th>")
                + Lang.T("<th>Usure SSD</th><th>Heures</th><th>Temp.</th><th>Source</th></tr></thead><tbody>", "<th>SSD wear</th><th>Hours</th><th>Temp.</th><th>Source</th></tr></thead><tbody>"));

        foreach (var d in disks)
        {
            var s = d.Smart!;
            bool bad = s.BadSectors > 0 || s.PredictedFailure == true || s.SpareExhausted;
            sb.Append($"<tr{(bad ? " class=\"oldrow\"" : "")}><td>{H(d.Model)}</td>");
            sb.Append($"<td>{Cnt(s.ReallocatedSectors)}</td><td>{Cnt(s.PendingSectors)}</td><td>{Cnt(s.UncorrectableSectors)}</td>");
            sb.Append($"<td>{Cnt(s.UdmaCrcErrors)}</td>");
            // Réserve de blocs : la valeur seule ne dit rien, c'est sa position par
            // rapport au seuil du constructeur qui compte.
            sb.Append("<td>");
            if (s.AvailableSparePercent is { } sp)
            {
                var th = s.AvailableSpareThresholdPercent;
                sb.Append(s.SpareExhausted ? $"<strong>{sp} %</strong>" : $"{sp} %");
                if (th is > 0) sb.Append(Lang.T($" <span class=\"small\">(seuil {th} %)</span>", $" <span class=\"small\">(threshold {th}%)</span>"));
            }
            else sb.Append('—');
            sb.Append("</td>");
            // « l » n'existe que dans le motif : le texte des deux langues est donc
            // calculé AVANT d'entrer dans l'interpolation, pas à l'intérieur.
            var usure = s.SsdLifeLeftPercent is { } l ? Lang.T($"{100 - l} % usé", $"{100 - l}% used") : "—";
            sb.Append($"<td>{usure}</td>");
            sb.Append($"<td>{(s.PowerOnHours is { } h ? $"{h}" : "—")}</td>");
            sb.Append($"<td>{(s.TemperatureC is { } t ? $"{t} °C" : "—")}</td>");
            sb.Append($"<td class=\"small\">{H(s.Source)}</td></tr>");

            // Alerte levée par le contrôleur lui-même : elle mérite sa propre ligne,
            // pas une case dans un tableau.
            if (s.CriticalWarning is { } w && w != 0)
                sb.Append(Lang.T($"<tr class=\"oldrow\"><td colspan=\"10\">⚠ <strong>{H(d.Model)} — alerte du contrôleur :</strong> ", $"<tr class=\"oldrow\"><td colspan=\"10\">⚠ <strong>{H(d.Model)} — controller alert:</strong> ")
                        + $"{H(Collectors.NvmeSmartReader.DescribeWarning(w))}</td></tr>");
        }
        sb.Append("</tbody></table>");
        sb.Append(Lang.T(
            "<p class=\"empty\">Sur un SSD <strong>NVMe</strong>, le disque ne compte pas en secteurs : "
            + "ce qui annonce sa fin est l'épuisement de sa <strong>réserve de blocs</strong> (comparée au seuil du "
            + "constructeur) et les <strong>erreurs d'intégrité</strong> — des données qu'il n'a pas su relire.</p>",
            "<p class=\"empty\">On an <strong>NVMe</strong> SSD, the drive does not count in sectors: "
            + "what announces its end is the exhaustion of its <strong>spare block reserve</strong> (compared against the "
            + "manufacturer's threshold) and the <strong>integrity errors</strong> — data it could not read back.</p>"));
        sb.Append(Lang.T(
            "<p class=\"empty\"><strong>« 0 » et « — » ne veulent pas dire la même chose :</strong> 0 est une mesure "
            + "(le compteur existe et vaut zéro, c'est le signe d'un disque sain), « — » signifie que ce compteur "
            + "n'est pas exposé par le disque et n'a donc pas été mesuré.<br>"
            + "Ce qui compte n'est pas tant la valeur absolue que son ÉVOLUTION : FaultTracePC la compare "
            + "automatiquement d'un scan à l'autre.</p></section>",
            "<p class=\"empty\"><strong>“0” and “—” do not mean the same thing:</strong> 0 is a measurement "
            + "(the counter exists and reads zero, which is the sign of a healthy drive), “—” means that this counter "
            + "is not exposed by the drive and therefore was not measured.<br>"
            + "What matters is not so much the absolute value as its TREND: FaultTracePC compares it "
            + "automatically from one scan to the next.</p></section>"));
    }

    private static string Cnt(ulong? v) => v is null ? "—" : v.Value == 0 ? "0" : $"<strong>{v}</strong>";

    private static void DriversSection(StringBuilder sb, DiagnosticReport r)
    {
        var thirdParty = r.System.Drivers
            .Where(d => d.State.Equals("Running", StringComparison.OrdinalIgnoreCase) && !d.IsMicrosoft && !string.IsNullOrEmpty(d.CompanyName))
            .OrderBy(d => d.CompanyName).ThenBy(d => d.Name).ToList();

        sb.Append(Lang.T("<section class=\"tech\"><h2>Pilotes tiers actifs</h2>", "<section class=\"tech\"><h2>Active third-party drivers</h2>"));
        sb.Append(Lang.T(
            "<p class=\"explain\">Un pilote est le petit programme qui fait le lien entre Windows et un matériel ou un outil. "
            + "Ceux listés ici ne viennent pas de Microsoft — ce sont les premiers à vérifier en cas d'écran bleu.",
            "<p class=\"explain\">A driver is the small program that links Windows to a piece of hardware or a tool. "
            + "Those listed here do not come from Microsoft — they are the first to check after a blue screen.") + "</p>");
        if (r.System.Drivers.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Inventaire des pilotes non collecté.</p></section>", "<p class=\"empty\">Driver inventory not collected.</p></section>")); return; }
        if (thirdParty.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Aucun pilote tiers en cours d'exécution (tous Microsoft).</p></section>", "<p class=\"empty\">No third-party driver running (all Microsoft).</p></section>")); return; }

        sb.Append(Lang.T($"<p class=\"sub2\">{thirdParty.Count} pilotes non-Microsoft en cours d'exécution — en cas de BSOD, ce sont les premiers suspects, surtout les plus anciens.</p>", $"<p class=\"sub2\">{thirdParty.Count} non-Microsoft drivers running — after a BSOD these are the first suspects, especially the oldest ones.</p>"));
        sb.Append(Lang.T(
            "<div class=\"legend\"><strong>Pourquoi certains pilotes sont marqués « ancien » :</strong> un fichier pilote de plus de 4 ans "
            + "n'est <em>pas</em> un problème en soi — s'il n'apparaît dans aucun crash, c'est simplement un suspect potentiel à connaître. "
            + "Les pilotes bas niveau anciens (lecteurs virtuels, antivirus, outils disque) sont en revanche des causes classiques de BSOD "
            + "lorsqu'ils sont impliqués : si un BSOD cite l'un d'eux, mettre à jour l'application associée ou la désinstaller si elle ne sert plus.</div>",
            "<div class=\"legend\"><strong>Why some drivers are marked “old”:</strong> a driver file more than 4 years old "
            + "is <em>not</em> a problem in itself — if it appears in no crash, it is simply a potential suspect worth knowing about. "
            + "Old low-level drivers (virtual drives, antivirus, disk tools) are, on the other hand, classic causes of BSODs "
            + "when they are involved: if a BSOD names one of them, update the associated application or uninstall it if it is no longer used.</div>"));
        sb.Append(Lang.T("<table><thead><tr><th>Pilote</th><th>Éditeur</th><th>Version</th><th>Date du fichier</th><th>Âge</th><th>Fichier</th>", "<table><thead><tr><th>Driver</th><th>Publisher</th><th>Version</th><th>File date</th><th>Age</th><th>File</th>")
                + Lang.T("<th>Connu de FaultTracePC ?</th></tr></thead><tbody>", "<th>Known to FaultTracePC?</th></tr></thead><tbody>"));
        int documented = 0, family = 0;
        foreach (var d in thirdParty)
        {
            bool isOld = d.FileDate is { } fd && fd < DateTime.Now.AddYears(-4);
            var ageBadge = d.FileDate is null ? "—"
                : isOld ? Lang.T($"<span class=\"agebadge\">ancien ({(int)((DateTime.Now - d.FileDate.Value).TotalDays / 365)} ans)</span>",
                                 $"<span class=\"agebadge\">old ({(int)((DateTime.Now - d.FileDate.Value).TotalDays / 365)} years)</span>")
                : Lang.T("récent", "recent");

            // Base de correspondance pilote → logiciel → action : quand le fichier y
            // figure, on affiche à QUOI il correspond et on met la marche à suivre en
            // infobulle. Un nom de fichier seul n'aide personne à réparer quoi que ce soit.
            var file = Path.GetFileName(d.Path);
            var hit = Analysis.DriverKnowledgeBase.LookupAny(file, d.CompanyName);
            string known;
            if (hit is { } h2)
            {
                if (h2.Exact) documented++; else family++;
                // Le point d'interrogation distingue une identification par FAMILLE
                // d'une correspondance nominative : le conseil reste valable, mais il
                // est générique. Laisser croire à une identification précise serait
                // une petite malhonnêteté qui finit par coûter cher.
                known = Lang.T($"<span class=\"kbhit\" title=\"{H(h2.Entry.Context)} — Que faire : {H(h2.Entry.Fix)}\">", $"<span class=\"kbhit\" title=\"{H(h2.Entry.Context)} — What to do: {H(h2.Entry.Fix)}\">")
                      + Lang.T($"{H(h2.Entry.Owner)}{(h2.Exact ? "" : " <span class=\"small\">(famille)</span>")}</span>", " <span class=\"small\">(family)</span>");
            }
            else known = "<span class=\"small\">—</span>";

            sb.Append($"<tr{(isOld ? " class=\"oldrow\"" : "")}><td>{H(FirstNonEmpty(d.DisplayName, d.Name))}</td><td>{H(d.CompanyName)}</td><td class=\"small\">{H(d.FileVersion)}</td>");
            sb.Append($"<td>{(d.FileDate is { } fdate ? Lang.Date(fdate) : "—")}</td><td>{ageBadge}</td><td class=\"small\">{H(file)}</td><td class=\"small\">{known}</td></tr>");
        }
        sb.Append("</tbody></table>");
        sb.Append(Lang.T(
            $"<p class=\"empty\">Sur {thirdParty.Count} pilote(s) tiers : <strong>{documented}</strong> identifié(s) nommément "
            + $"(base de {Analysis.DriverKnowledgeBase.Count} pilotes documentés), <strong>{family}</strong> rattaché(s) à une famille "
            + $"connue, {thirdParty.Count - documented - family} non documenté(s). Survole la dernière colonne pour savoir à quel logiciel "
            + "un pilote appartient et quoi faire s'il est impliqué dans un crash.<br>"
            + "« (famille) » signale une identification par plateforme : le conseil est valable mais générique, contrairement à une "
            + "correspondance nominative qui donne le correctif éprouvé. Un tiret ne veut pas dire suspect — seulement non documenté.</p>",
            $"<p class=\"empty\">Out of {thirdParty.Count} third-party driver(s): <strong>{documented}</strong> identified by name "
            + $"(from a base of {Analysis.DriverKnowledgeBase.Count} documented drivers), <strong>{family}</strong> matched to a known "
            + $"family, {thirdParty.Count - documented - family} undocumented. Hover the last column to see which software "
            + "a driver belongs to and what to do if it is involved in a crash.<br>"
            + "“(family)” marks an identification by platform: the advice holds but is generic, unlike a by-name "
            + "match, which gives the proven fix. A dash does not mean suspect — only undocumented.</p>"));
        sb.Append("</section>");
    }

    private static void ReliabilitySection(StringBuilder sb, DiagnosticReport r)
    {
        sb.Append(Lang.T("<section class=\"tech\"><h2>Moniteur de fiabilité</h2>", "<section class=\"tech\"><h2>Reliability monitor</h2>"));
        sb.Append(Lang.T("<p class=\"explain\">L'historique de stabilité que Windows tient en continu — installations, plantages, mises à jour.</p>", "<p class=\"explain\">The stability history Windows keeps continuously — installations, crashes, updates.</p>"));
        if (r.ReliabilityRecords.Count == 0) { sb.Append(Lang.T("<p class=\"empty\">Aucune donnée de fiabilité disponible sur la période.</p></section>", "<p class=\"empty\">No reliability data available over the period.</p></section>")); return; }
        sb.Append(Lang.T("<table><thead><tr><th>Date</th><th>Source</th><th>Produit</th><th>Message</th></tr></thead><tbody>", "<table><thead><tr><th>Date</th><th>Source</th><th>Product</th><th>Message</th></tr></thead><tbody>"));
        foreach (var rec in r.ReliabilityRecords.Take(60))
            sb.Append($"<tr><td>{Lang.ShortDateMinute(rec.TimeLocal)}</td><td class=\"small\">{H(rec.SourceName)}</td><td class=\"small\">{H(rec.ProductName)}</td><td class=\"small\">{H(Shorten(rec.Message, 160))}</td></tr>");
        sb.Append("</tbody></table></section>");
    }

    private static void ErrorsSection(StringBuilder sb, DiagnosticReport r)
    {
        // Deux sections distinctes : ce qui a échoué, et ce qui a été fait. Mélanger
        // un entretien normal avec des limitations le ferait passer pour un problème.
        if (r.Notes.Count > 0)
        {
            sb.Append(Lang.T("<section><h2>Entretien effectué</h2><ul>", "<section><h2>Maintenance performed</h2><ul>"));
            foreach (var n in r.Notes)
                sb.Append($"<li>{H(n)}</li>");
            sb.Append("</ul></section>");
        }

        if (r.CollectorErrors.Count == 0) return;
        sb.Append(Lang.T("<section><h2>Limitations de cette analyse</h2><ul>", "<section><h2>Limitations of this analysis</h2><ul>"));
        foreach (var e in r.CollectorErrors)
            sb.Append($"<li>{H(e)}</li>");
        sb.Append(Lang.T("</ul><p class=\"empty\">Ces sources n'ont pas pu être lues ; le diagnostic reste valable sur les données collectées.</p></section>", "</ul><p class=\"empty\">These sources could not be read; the diagnosis remains valid on the data collected.</p></section>"));
    }

    // ------------------------------------------------------------------

    private static void Card(StringBuilder sb, string title, string html) =>
        sb.Append($"<div class=\"syscard\"><h4>{H(title)}</h4><p>{html}</p></div>");

    private static string CategoryLabel(FaultCategory c) => c switch
    {
        FaultCategory.Hardware => Lang.T("Matériel", "Hardware"),
        FaultCategory.Memory => Lang.T("Mémoire RAM", "RAM"),
        FaultCategory.Storage => Lang.T("Stockage", "Storage"),
        FaultCategory.GpuDriver => Lang.T("Pilote graphique", "Display driver"),
        FaultCategory.Driver => Lang.T("Pilote", "Driver"),
        FaultCategory.Software => Lang.T("Logiciel", "Software"),
        FaultCategory.Power => Lang.T("Alimentation", "Power"),
        // « Windows Update » est un nom de produit : identique dans les deux langues.
        FaultCategory.WindowsUpdate => "Windows Update",
        _ => Lang.T("Général", "General"),
    };

    private static string CategoryEventLabel(EventCategory c) => c switch
    {
        EventCategory.Bsod => "BSOD",
        EventCategory.PowerLoss => Lang.T("Coupure (Kernel-Power 41)", "Power loss (Kernel-Power 41)"),
        EventCategory.UnexpectedShutdown => Lang.T("Arrêt inattendu", "Unexpected shutdown"),
        EventCategory.Whea => Lang.T("Erreur matérielle (WHEA)", "Hardware error (WHEA)"),
        EventCategory.DiskError => Lang.T("Erreur disque", "Disk error"),
        EventCategory.Tdr => Lang.T("Réinit. pilote graphique", "Display driver reset"),
        EventCategory.AppCrash => Lang.T("Crash application", "Application crash"),
        EventCategory.AppHang => Lang.T("Application bloquée", "Application hang"),
        EventCategory.ServiceFailure => Lang.T("Échec de service", "Service failure"),
        EventCategory.MemoryDiag => Lang.T("Diagnostic mémoire", "Memory diagnostic"),
        EventCategory.WindowsUpdate => "Windows Update",
        EventCategory.ResourceExhaustion => Lang.T("Saturation mémoire", "Memory exhaustion"),
        _ => Lang.T("Autre", "Other"),
    };

    /// <summary>JS du rapport : réouverture des blocs repliés à l'impression, bascule
    /// simple/complet, filtrage des événements par catégorie.</summary>
    /// <remarks>
    /// CETTE EXEMPTION A ÉTÉ FAUSSE JUSQU'EN 1.4, ET C'EST INSTRUCTIF.
    /// Sa justification disait « aucun texte affiché ». C'était vrai de presque
    /// tout le script, et faux de deux lignes : il réécrivait le libellé du bouton
    /// de bascule en français en dur. L'exemption couvrant le littéral ENTIER,
    /// aucun test ne pouvait le signaler — et comme le libellé initial était
    /// correct, la fuite ne se voyait qu'après un clic.
    ///
    /// Les deux libellés sont désormais injectés depuis Lang.T (objet FTPC_L,
    /// écrit juste avant ce script). La justification est redevenue vraie.
    ///
    /// Le marqueur ci-dessous doit rester COLLÉ au littéral : le test ne le cherche
    /// que sur la ligne du littéral ou celle qui la précède. L'en éloigner d'un
    /// paragraphe suffit à faire tomber l'exemption — c'est arrivé en écrivant ces
    /// lignes, et le test l'a vu tout de suite.
    /// </remarks>
    // pas-de-traduction : du JavaScript, plus aucun texte affiché depuis la 1.4.
    private const string FilterJs = """
        (function(){
          // Printing and PDF export: everything folded is reopened, then restored.
          // A document handed to a repair shop must not be truncated without its
          // recipient knowing. Done here IN ADDITION to the CSS rule, because how a
          // closed <details> prints depends on the engine.
          const folds = () => document.querySelectorAll('details');
          addEventListener('beforeprint', () => folds().forEach(d => { d.dataset.o = d.open ? '1' : ''; d.open = true; }));
          addEventListener('afterprint', () => folds().forEach(d => { d.open = d.dataset.o === '1'; }));

          const t = document.getElementById('mode-toggle');
          if (t) t.addEventListener('click', () => {
            const simple = document.body.classList.toggle('simple');
            t.textContent = simple ? FTPC_L.complet : FTPC_L.simple;
          });
          const chips = document.querySelectorAll('#evt-chips .chip');
          const rows = document.querySelectorAll('#evt-table tbody tr');
          const none = document.getElementById('evt-none');
          if (!chips.length) return;
          chips.forEach(c => c.addEventListener('click', () => {
            chips.forEach(x => x.classList.remove('active'));
            c.classList.add('active');
            const cat = c.dataset.cat;
            let visible = 0;
            rows.forEach(tr => {
              const show = (cat === 'all' || tr.dataset.cat === cat);
              tr.style.display = show ? '' : 'none';
              if (show) visible++;
            });
            if (none) none.style.display = visible === 0 ? '' : 'none';
          }));
        })();
        """;

    /// <summary>
    /// Les deux états du bouton de bascule.
    ///
    /// Ils vivent ici parce qu'ils sont écrits à DEUX endroits : dans le bouton
    /// rendu par le serveur, et dans le script qui le réécrit au clic. Le script
    /// est une constante — il ne peut contenir aucun appel de traduction — et il
    /// contenait donc les libellés français en dur : dans le rapport anglais,
    /// cliquer sur le bouton le faisait basculer en français. Le libellé initial
    /// étant correct, la fuite ne se voyait qu'après un clic, et aucun test ne
    /// clique.
    ///
    /// Des propriétés, pas des champs « static readonly » : ceux-ci figeraient la
    /// langue au premier accès au type.
    /// </summary>
    private static string BasculeVersComplet =>
        Lang.T("🔎 Afficher les détails techniques (mode complet)", "🔎 Show the technical detail (full mode)");

    private static string BasculeVersSimple =>
        Lang.T("🙈 Masquer les détails techniques (mode simple)", "🙈 Hide the technical detail (simple mode)");

    /// <summary>Un littéral JavaScript sûr, échappement compris.</summary>
    private static string Js(string s) => System.Text.Json.JsonSerializer.Serialize(s);

    private static string FirstNonEmpty(params string[] values) =>
        values.FirstOrDefault(v => !string.IsNullOrWhiteSpace(v)) ?? "";

    /// <summary>
    /// État de santé affichable d'un disque. Quand rien n'a été rapporté, on retombe
    /// sur la valeur brute de WMI (« OK », « Degraded », « Pred Fail ») : c'est un mot
    /// de Windows, pas du nôtre — il n'est donc pas traduit. Seul le dernier recours
    /// l'est, faute de quoi un rapport anglais afficherait « santé : inconnue ».
    /// </summary>
    private static string SanteLisible(DiskInfo d) =>
        d.Health == DiskHealth.NotReported
            ? FirstNonEmpty(d.WmiStatus, Lang.T("inconnue", "unknown"))
            : d.Health.Label();

    private static string Shorten(string s, int max) => s.Length <= max ? s : s[..max] + "…";

    private static string H(string? s) => System.Net.WebUtility.HtmlEncode(s ?? "");

    // pas-de-traduction : de la CSS, aucun texte affiché.
    private const string Css = """
        :root{color-scheme:light}
        *{box-sizing:border-box}
        body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;background:#f4f6f9;color:#1d2733;line-height:1.5}
        header{background:#182848;color:#fff;padding:26px 34px}
        header h1{margin:0;font-size:24px;font-weight:600}
        .brand{display:flex;align-items:center;gap:14px}
        .brand img{border-radius:8px;flex:0 0 auto}
        header .sub{margin:6px 0 0;opacity:.85;font-size:14px}
        section{max-width:1160px;margin:26px auto;padding:0 24px}
        h2{font-size:19px;border-bottom:2px solid #dbe2ec;padding-bottom:6px;margin:0 0 14px}
        .verdict{max-width:1160px;margin:24px auto 0;padding:18px 24px;border-radius:10px;display:flex;gap:18px;align-items:center;margin-left:auto;margin-right:auto;width:calc(100% - 48px)}
        .verdict.crit{background:#fdecea;border:1px solid #e74c3c}
        .verdict.warn{background:#fef5e7;border:1px solid #e67e22}
        .verdict.ok{background:#eafaf1;border:1px solid #27ae60}
        .verdict-label{font-size:12px;text-transform:uppercase;letter-spacing:1px;font-weight:700;opacity:.7}
        .verdict-text{font-size:16px;font-weight:600}
        .card{background:#fff;border:1px solid #dbe2ec;border-left-width:5px;border-radius:8px;padding:14px 18px;margin-bottom:12px}
        .card.crit{border-left-color:#e74c3c}.card.warn{border-left-color:#e67e22}.card.info{border-left-color:#2980b9}
        .card.okcard{border-left-color:#27ae60;background:#f4fbf7}
        .concerns{margin:.6em 0 .4em;padding-left:1.2em}
        .concerns li{margin:.35em 0;line-height:1.45}
        .concerns li.crit{font-weight:600}
        .toolhint{margin:.5em 0 0;font-size:13px;background:#f0f4fa;border-left:3px solid #2470B3;padding:7px 11px;border-radius:0 5px 5px 0}
        .toollabel{font-weight:600;color:#1d4f7f;margin-right:6px}
        .ctxtitle{margin:14px 0 6px;font-size:13px;color:#44546a}
        .card h3{margin:8px 0 6px;font-size:16px}
        .card p{margin:4px 0;font-size:14px}
        .card .reco{background:#eafaf1;border:1px solid #bfe8d0;border-radius:6px;padding:9px 11px;margin-top:8px}
        .recolabel{display:inline-block;background:#27ae60;color:#fff;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;padding:2px 9px;border-radius:12px;margin-right:6px;animation:recopulse 1.1s ease-in-out 3}
        @keyframes recopulse{0%,100%{transform:scale(1);box-shadow:none}50%{transform:scale(1.12);box-shadow:0 0 0 6px rgba(39,174,96,.25)}}
        .card-head{display:flex;justify-content:space-between;align-items:center}
        .badge{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.5px;padding:3px 9px;border-radius:20px;color:#fff}
        .badge.crit{background:#e74c3c}.badge.warn{background:#e67e22}.badge.info{background:#2980b9}
        .conf{font-size:12px;color:#5a6b7f}
        table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #dbe2ec;border-radius:8px;overflow:hidden;font-size:13px}
        th{background:#eef2f7;text-align:left;padding:8px 10px;font-size:12px;text-transform:uppercase;letter-spacing:.4px;color:#44546a}
        td{padding:7px 10px;border-top:1px solid #e8edf3;vertical-align:top}
        tr:hover td{background:#f7fafc}
        .oldrow td{background:#fff8ef}
        .mono{font-family:Consolas,monospace}
        .small{font-size:12px;color:#42546b}
        .extract{color:#1a6fb5;font-size:12px}
        .empty{color:#6b7c91;font-size:13px;font-style:italic}
        .sub2{color:#44546a;font-size:13px;margin:0 0 10px}
        .chips{margin:0 0 12px}
        .chip{display:inline-block;background:#fff;border:1px solid #dbe2ec;border-radius:16px;padding:4px 12px;font-size:12px;margin:0 6px 6px 0;cursor:pointer;font-family:inherit;color:inherit}
        .chip:hover{border-color:#2470b3;background:#f0f6fc}
        .chip.active{background:#2470b3;border-color:#2470b3;color:#fff}
        .legend{background:#fffbe9;border:1px solid #e8d9a0;border-radius:8px;padding:10px 14px;font-size:13px;margin:0 0 12px}
        .explain{color:#5a6b7f;font-size:13px;font-style:italic;margin:0 0 12px}
        .bigstep{font-size:15px;background:#eafaf1;border-radius:6px;padding:10px 12px}
        .btn2{margin-top:12px;background:rgba(255,255,255,.12);color:#fff;border:1px solid rgba(255,255,255,.35);border-radius:6px;padding:7px 14px;font-size:12px;cursor:pointer;font-family:inherit}
        .btn2:hover{background:rgba(255,255,255,.22)}
        body.simple section.tech{display:none}
        .fold{margin:0 0 18px}
        .fold>summary{cursor:pointer;font-weight:600;color:#2A78D6;padding:8px 0;list-style:revert}
        .fold>summary:hover{text-decoration:underline}
        @media print{
          /* Un PDF transmis à un réparateur ne doit pas être amputé : tout ce qui
             est replié à l'écran se rouvre à l'impression. La règle CSS et le
             gestionnaire beforeprint font double emploi VOLONTAIREMENT — le
             comportement d'un <details> fermé à l'impression dépend du moteur. */
          details>*{display:block!important}
          /* Un rapport imprimé ou exporté en PDF ne doit pas couper une conclusion
             en deux : chaque carte reste d'un seul tenant, et le bouton de bascule
             n'a évidemment aucun sens sur papier. */
          #mode-toggle,.filterbar{display:none!important}
          body{background:#fff}
          .card,.syscard,.repair,.guided,.verdict{break-inside:avoid;page-break-inside:avoid}
          section{break-inside:auto}
          h2{break-after:avoid;page-break-after:avoid}
          table{font-size:10px}
          a{color:#000;text-decoration:none}
        }
        .guided{background:#f2ecf7;border:1px solid #7D3C98;border-left:5px solid #7D3C98;border-radius:8px;padding:14px 18px;margin:0 0 18px;font-size:13px}
        .guided-t{font-weight:700;color:#5B2C6F;font-size:14px;margin-bottom:6px}
        .guided p{margin:6px 0 0}
        .kbhit{border-bottom:1px dotted #2A78D6;cursor:help;color:#2A78D6}
        .agebadge{background:#e6a817;color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:12px;white-space:nowrap}
        .repair{background:#fff;border:1px solid #dbe2ec;border-left:5px solid #27ae60;border-radius:8px;padding:14px 18px;font-size:14px}
        .repair pre{background:#182848;color:#d8e4f5;padding:10px 12px;border-radius:6px;overflow-x:auto;font-size:12px}
        .stack{background:#182848;color:#d8e4f5;padding:8px 10px;border-radius:6px;overflow-x:auto;font-size:11px;line-height:1.4;margin:4px 0 0}
        details summary{cursor:pointer;color:#2470b3}
        .repair code{background:#eef2f7;padding:1px 5px;border-radius:4px;font-size:12px}
        .btn{background:#27ae60;color:#fff;border:0;border-radius:6px;padding:9px 16px;font-size:13px;font-weight:600;cursor:pointer;font-family:inherit}
        .btn:hover{background:#219652}
        .grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:12px}
        .syscard{background:#fff;border:1px solid #dbe2ec;border-radius:8px;padding:12px 16px}
        .syscard h4{margin:0 0 6px;font-size:13px;text-transform:uppercase;letter-spacing:.5px;color:#44546a}
        .syscard p{margin:0;font-size:13px}
        footer{max-width:1160px;margin:30px auto;padding:14px 24px;color:#6b7c91;font-size:12px;border-top:1px solid #dbe2ec}
        """;
}
