namespace FaultTracePC.Core.Analysis;

public sealed record BugCheckEntry(
    string Name,
    FaultCategory Category,
    string Description,
    string Advice);

/// <summary>
/// Catalogue des codes STOP les plus fréquents, avec catégorie de cause probable
/// et conseils en français. Référence : documentation "Bug Check Code Reference"
/// de Microsoft (learn.microsoft.com).
/// </summary>
public static class BugCheckCatalog
{
    public static BugCheckEntry? Lookup(uint code) =>
        Entries.TryGetValue(code, out var e) ? e : null;

    public static string NameOf(uint code) =>
        Lookup(code)?.Name ?? $"BUGCODE_0x{code:X}";

    public static readonly IReadOnlyDictionary<uint, BugCheckEntry> Entries = new Dictionary<uint, BugCheckEntry>
    {
        [0x0A] = new("IRQL_NOT_LESS_OR_EQUAL", FaultCategory.Driver,
            "Accès mémoire invalide à un niveau d'interruption trop élevé — très souvent un pilote défectueux, parfois la RAM.",
            "Mettre à jour les pilotes récents ; tester la RAM si récurrent sans pilote identifié."),
        [0x1A] = new("MEMORY_MANAGEMENT", FaultCategory.Memory,
            "Erreur grave du gestionnaire de mémoire — RAM défectueuse, pilote corrompant la mémoire, ou fichier d'échange endommagé.",
            "Lancer le diagnostic mémoire Windows (mdsched.exe) puis MemTest86 sur plusieurs passes ; retirer tout overclocking XMP le temps du test."),
        [0x1E] = new("KMODE_EXCEPTION_NOT_HANDLED", FaultCategory.Driver,
            "Exception non gérée en mode noyau — pilote ou incompatibilité matérielle.",
            "Identifier le module cité, mettre à jour ou désinstaller le pilote correspondant."),
        [0x24] = new("NTFS_FILE_SYSTEM", FaultCategory.Storage,
            "Erreur dans le pilote NTFS — disque défaillant ou système de fichiers corrompu.",
            "Exécuter chkdsk /f /r et vérifier la santé SMART du disque."),
        [0x3B] = new("SYSTEM_SERVICE_EXCEPTION", FaultCategory.Driver,
            "Exception dans un service système — pilote graphique ou antivirus fréquemment en cause.",
            "Mettre à jour pilote graphique et solutions de sécurité ; vérifier les fichiers système (sfc /scannow)."),
        [0x50] = new("PAGE_FAULT_IN_NONPAGED_AREA", FaultCategory.Memory,
            "Référence à une mémoire système invalide — RAM défectueuse, pilote, ou antivirus.",
            "Diagnostic mémoire ; désinstaller logiciel/pilote installé juste avant l'apparition du problème."),
        [0x7A] = new("KERNEL_DATA_INPAGE_ERROR", FaultCategory.Storage,
            "Échec de lecture de données noyau depuis le fichier d'échange — disque ou câblage défaillant, parfois RAM.",
            "Vérifier SMART, câbles SATA/alimentation, chkdsk ; tester la RAM en second."),
        [0x7E] = new("SYSTEM_THREAD_EXCEPTION_NOT_HANDLED", FaultCategory.Driver,
            "Exception non gérée dans un thread système — pilote presque toujours en cause.",
            "Le nom du pilote apparaît souvent dans les paramètres/le dump : le mettre à jour ou le restaurer."),
        [0x9F] = new("DRIVER_POWER_STATE_FAILURE", FaultCategory.Driver,
            "Un pilote n'a pas répondu à une transition d'alimentation (veille/reprise).",
            "Mettre à jour pilotes réseau/graphique/chipset ; tester en désactivant la mise en veille rapide."),
        [0xC2] = new("BAD_POOL_CALLER", FaultCategory.Driver,
            "Allocation mémoire noyau invalide — pilote défectueux.",
            "Identifier le pilote via le dump ; vérifier pilotes récemment installés."),
        [0xC5] = new("DRIVER_CORRUPTED_EXPOOL", FaultCategory.Driver,
            "Corruption du pool noyau par un pilote.",
            "Activer le vérificateur de pilotes (verifier.exe) pour identifier le fautif."),
        [0xD1] = new("DRIVER_IRQL_NOT_LESS_OR_EQUAL", FaultCategory.Driver,
            "Un pilote a accédé à une mémoire paginée à un IRQL trop élevé — pilote réseau/stockage souvent en cause.",
            "Mettre à jour le pilote cité dans le dump (souvent un .sys réseau, Wi-Fi ou antivirus)."),
        [0xEF] = new("CRITICAL_PROCESS_DIED", FaultCategory.Software,
            "Un processus système critique s'est arrêté (csrss, wininit…) — corruption système, disque, parfois malware.",
            "sfc /scannow puis DISM /Online /Cleanup-Image /RestoreHealth ; vérifier le disque système."),
        [0xF4] = new("CRITICAL_OBJECT_TERMINATION", FaultCategory.Storage,
            "Arrêt d'un objet critique — très souvent lié à un disque système défaillant ou déconnecté.",
            "Vérifier SMART et câblage du disque système en priorité."),
        [0x101] = new("CLOCK_WATCHDOG_TIMEOUT", FaultCategory.Hardware,
            "Un cœur CPU n'a pas répondu aux interruptions — CPU, surchauffe, overclocking ou BIOS.",
            "Retirer tout overclocking, vérifier températures CPU et mettre à jour le BIOS."),
        [0x116] = new("VIDEO_TDR_FAILURE", FaultCategory.GpuDriver,
            "Le pilote graphique n'a pas répondu (TDR) — pilote GPU, surchauffe GPU ou carte défaillante.",
            "Installation propre du pilote GPU (DDU) ; surveiller la température GPU ; tester sans overclocking."),
        [0x117] = new("VIDEO_TDR_TIMEOUT_DETECTED", FaultCategory.GpuDriver,
            "Réinitialisation du pilote graphique après blocage.",
            "Mêmes vérifications que VIDEO_TDR_FAILURE (pilote GPU, température, alimentation de la carte)."),
        [0x119] = new("VIDEO_SCHEDULER_INTERNAL_ERROR", FaultCategory.GpuDriver,
            "Erreur interne du planificateur vidéo — pilote GPU.",
            "Installation propre du pilote graphique."),
        [0x124] = new("WHEA_UNCORRECTABLE_ERROR", FaultCategory.Hardware,
            "Erreur matérielle fatale remontée par le processeur (WHEA) — CPU, carte mère, alimentation, surchauffe ou overclocking instable.",
            "Vérifier températures et alimentation ; retirer l'overclocking/XMP ; mettre à jour le BIOS ; si récurrent, suspecter CPU/carte mère."),
        [0x133] = new("DPC_WATCHDOG_VIOLATION", FaultCategory.Driver,
            "Une routine différée (DPC) a dépassé le temps imparti — pilote de stockage (SSD/NVMe) ou firmware fréquemment en cause.",
            "Mettre à jour firmware SSD et pilotes de stockage (stornvme/iaStor), ainsi que les pilotes chipset."),
        [0x139] = new("KERNEL_SECURITY_CHECK_FAILURE", FaultCategory.Driver,
            "Corruption détectée par une vérification de sécurité du noyau — pilote ou RAM.",
            "Diagnostic mémoire + mise à jour des pilotes ; sfc /scannow."),
        [0x13A] = new("KERNEL_MODE_HEAP_CORRUPTION", FaultCategory.Driver,
            "Corruption du tas noyau — pilote (souvent graphique) ou RAM.",
            "Mettre à jour le pilote graphique ; tester la RAM."),
        [0x154] = new("UNEXPECTED_STORE_EXCEPTION", FaultCategory.Storage,
            "Exception dans le gestionnaire de mémoire compressée — souvent disque/SSD défaillant.",
            "Vérifier la santé du disque système (SMART) et son firmware."),
        [0x1CA] = new("SYNTHETIC_WATCHDOG_TIMEOUT", FaultCategory.Software,
            "Le système n'a plus répondu (watchdog) — cause logicielle ou stockage.",
            "Examiner les événements disque autour du crash."),
        [0xA0] = new("INTERNAL_POWER_ERROR", FaultCategory.Power,
            "Erreur interne du gestionnaire d'alimentation.",
            "Mettre à jour BIOS et pilotes chipset ; vérifier les paramètres d'alimentation."),
        [0x7F] = new("UNEXPECTED_KERNEL_MODE_TRAP", FaultCategory.Hardware,
            "Interruption inattendue en mode noyau — RAM/CPU/overclocking ou pilote bas niveau.",
            "Retirer l'overclocking, tester la RAM ; vérifier les températures."),
        [0x4E] = new("PFN_LIST_CORRUPT", FaultCategory.Memory,
            "Liste des pages mémoire corrompue — RAM défectueuse très probable.",
            "MemTest86 sur plusieurs passes ; tester les barrettes une par une."),
        [0x12B] = new("FAULTY_HARDWARE_CORRUPTED_PAGE", FaultCategory.Memory,
            "Page mémoire corrompue détectée — RAM défectueuse probable.",
            "Diagnostic mémoire approfondi ; vérifier aussi le fichier d'échange et le disque."),
        [0xDE] = new("POOL_CORRUPTION_IN_FILE_AREA", FaultCategory.Storage,
            "Corruption mémoire dans une zone fichier.",
            "chkdsk + vérification SMART."),
        [0xEA] = new("THREAD_STUCK_IN_DEVICE_DRIVER", FaultCategory.GpuDriver,
            "Un thread tourne en boucle dans un pilote de périphérique — GPU en général.",
            "Installation propre du pilote graphique ; vérifier la carte."),
        [0xFC] = new("ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY", FaultCategory.Driver,
            "Tentative d'exécution d'une zone non exécutable — pilote défectueux ou RAM.",
            "Mettre à jour les pilotes ; tester la RAM."),
        [0x18B] = new("CRITICAL_STRUCTURE_CORRUPTION_LIVEDUMP", FaultCategory.Driver,
            "Corruption de structure critique détectée (live dump).",
            "Examiner les pilotes non signés ou récemment mis à jour."),
    };
}
